### ISSUE TITLE
add api so one can make searches with autosuggestions from some external source

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#10]
I want to have the ability to extend [this workflow](https://github.com/deanishe/alfred-searchio) with this search engine.

**Comment by nikitavoloboev** [comment]
You can parse triggers.js file and output that to alfred.

**Comment by nikitavoloboev** [comment]
In future it is best to provide stand alone API for that.

**Comment by mattburman** [comment]
I was going to make a separate issue for implementing standard URL scheme for searching -
 https://url.spec.whatwg.org/#urlsearchparams. But I guess this is similar and probably wants to be designed at the same time.

Basically a `q=searchquery` parameter would be good to support
