### ISSUE TITLE
show path to all rendered mind maps on the web page

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#18]
And make it interactive so all words are hyperlinks.

**Comment by ewnd9** [comment]
![2017-05-30t20 44 34 102z](https://cloud.githubusercontent.com/assets/1713789/26604390/cebe1dba-45bc-11e7-8ea8-8875cd3c9797.png)

This is how it might look with 

```html
<div style="text-align: center;">
  Mathematics / <b>Linear Algebra</b>
</div>
```

below the form, where "Mathematics" is a parent node and "Linear Algebra" is an active

**Comment by nglgzz** [comment]
`window.location.href` can be used to find the current URL.

**Comment by nikitavoloboev** [comment]
done 🎊
