### ISSUE TITLE
add twitter logo

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#22]
as simple icon

**Comment by tendaitt** [comment]
Will this log be at the bottom left corner with all the other icons?

**Comment by nikitavoloboev** [comment]
Yeah I was thinking here would be a good place : 

![2017-05-30 at 17 32](https://cloud.githubusercontent.com/assets/6391776/26591457/0585e404-455e-11e7-9764-6061a5352055.png)

Just the icon, no need for text. :)

**Comment by tendaitt** [comment]
Cool! Will work on it! :)

**Comment by nglgzz** [comment]
@tendaitt you may want to look at [this file](https://github.com/learn-anything/search-engine/blob/master/client/sass/main.sass) for styling the icon color when is being hovered.
