### ISSUE TITLE
fix back button overriding 

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#37]
I think this will be fixed once we move to D3.js.

**Comment by nglgzz** [comment]
Actually this won't be fixed with D3.js, and the problem lies somewhere else. It's just a matter of tweaking this line `window.history.pushState(null, null, url);` on `client/reducers/mapReducer.js` so that the new url doesn't override the old one.

**Comment by nglgzz** [comment]
I checked more on this, that line was correct, and the problem was that `window.history` was conflicting with `react-router-dom`. This should be fixed after refactoring on v2 branch.
