### ISSUE TITLE
make it so the entire node is clickable, not just the text inside the node

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#39]
Currently if I click on the edges of this node : 

![2017-06-12 at 21 06](https://user-images.githubusercontent.com/6391776/27050483-fcd32952-4fb2-11e7-8e4c-5140a5f0d516.png)

Nothing happens. You have to click on the text inside. I think it is best to make the entire node clickable for better user experience.

**Comment by GavinFreud** [comment]
Could I try my hand on this one? Never actually worked with JS on an open source project so this should be fun.

**Comment by nikitavoloboev** [comment]
Yeah of course. Thank you. 💙

If you want some help or guidance, we have a [slack team](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ) you can join. :)

**Comment by nynevi** [comment]
@GavinFreud at the moment the links are not stored in an object i.e:
`node: {
    linkUrl: "url",
    linkTitle: "title",
    linkEmoji: "emoji"
}`
but rather stored inside a string as can be seen here: https://github.com/learn-anything/react-mindmap#nodes

As you wanted to try your hand on this one I'll skip this but in case you are stuck the method I was thinking of is to find "href=\" inside text then get the url inside the quotes then attach an onclick handler on the p tag inside foreignObject with cursor: pointer as css on hover.

Tried it with css but no luck with height/width 100% without breaking all the layout.

**Comment by nglgzz** [comment]
I fixed this on `react-mindmap`, the change won't be propagated to the search engine until I'm done with the new contribution system. I'm closing this issue to avoid confusion.
