### ISSUE TITLE
Indicate that a node is a hyperlink and not an empty node

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#40]
For some cases, a node may be a link to a place but may not have an appropriate emoji attached to it so user does not know that this node is a link unless he clicks on it.

There should be some indication that a node is a hyperlink perhaps or we have to create some emoji for this case. Mind node for example underlines all nodes that are hyperlinks.

**Comment by iifeoluwa** [comment]
Hey @nikitavoloboev can you please provide a link to a map that has nodes which are just links?

**Comment by nikitavoloboev** [comment]
For example [here](https://learn-anything.xyz/programming/software_development/devops) 

![2017-06-13 at 14 08](https://user-images.githubusercontent.com/6391776/27081681-cc9d1ee8-5041-11e7-9c9f-52042a8a4b41.png)

There is no way to see that these nodes are clickable unless you hover over them.

**Comment by iifeoluwa** [comment]
Oh, alright. I'll like to take a crack at this. What do you think of this emoji?🔗

**Comment by nikitavoloboev** [comment]
I am not sure if new emoji is the correct way to do this. Since if you want to indicate a hyperlink with emoji, all nodes will need to have this emoji too which is bad. I was thinking of perhaps underlining all nodes that are hyperlinks but again I am not sure what is the best solution for this.

**Comment by iifeoluwa** [comment]
Oh, I see. Underlining is a good idea but I was thinking we'd do something that's consistent with how the app presentation works currently. Didn't realize the affect would be so widespread.

Can you please give a quick rundown of how emojis get added to the nodes? This would help in determining if we should introduce an emoji for nodes that are links or just use the underline.

**Comment by nikitavoloboev** [comment]
All maps are on mindnode and I add emojis there. We then take the JSON representation of these mindnode maps and show it in our search engine.

**Comment by nynevi** [comment]
Nodes with links will be indicated by an anchor emoji after the merge of by learn-anything/react-mindmap#11
