### ISSUE TITLE
Randomizer

### ISSUE THREAD

**Issue by Katamori** [learn-anything/search-engine#41]
Feature request*: ~~~add a randomizer button to the UI, either on the bottom, or besides the textbox, that randomly chooses one map out of the many.~~~ Nevermind, it'll be enough to apply initiating search on the random text that is already appearing in the textbox.

*if no one has the desire to make it, I'll do it ASAP, can't be hard.

**Comment by nikitavoloboev** [comment]
Yeah you can make it. :)

**Comment by nglgzz** [comment]
I like the idea too. 

I think a cool way would be when one presses enter on the empty searchbar, the random suggestion that is currently displayed as a placeholder is loaded. 

What do you guys think?

**Comment by nikitavoloboev** [comment]
Oh, that's really neat. I 💙 it.

**Comment by Katamori** [comment]
@nglgzz I actually *expected* that to happen, so it might even be a slightly important task to do - this way it's a little bit confusing.

**Comment by nglgzz** [comment]
Yeah that's what I thought. We often get empty queries so it might be that. Sure you can try and do that, it shouldn't be too hard. 

You may want to look at the `client/containers/Searchbar.jsk` file, on the onSubmit function.

**Comment by Katamori** [comment]
Now, reacting (no pun intended) to Enter is quite sensitive, somehow that should be resolved.

Is that relevant to this issue? If now, feel free to close this one.

**Comment by nglgzz** [comment]
What do you mean quite sensitive?

**Comment by Katamori** [comment]
Try it ;) jokes aside, I can't describe any better, it has a very small "waiting time", so you can easily skip results.

Maybe not a big deal though, because you can go back in history.
