### ISSUE TITLE
Opening links on Safari with Adblock has a long delay

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/search-engine#47]
And for some reason whitelisting the website does not work too. Everything works well on Chrome however.

Perhaps we can rewrite the functions for catching link presses to fix this.

**Comment by nglgzz** [comment]
It's not really a bug. Adblock is blocking requests to GA, so the callback (for opening links) is called after a timeout. 

The solution for this would be removing the async callback, and open the new tab right after the GA call is made. It would be pretty similar to how GA calls are made on `client/containers/SearchBar.jsx`, on the `onSuggestionSelected` function.

**Comment by nikitavoloboev** [comment]
Thanks @nglgzz 💚
