### ISSUE TITLE
Add a bottom to the suggestions bar

### ISSUE THREAD

**Issue by mattdax** [learn-anything/search-engine#53]
I think this is quite an easy fix.

Users can get confused when the scrolling down in the suggestion bar never stops and keeps repeating. Adding a bottom to the suggestion when they have gone through all of the options would make sense.

**Comment by nglgzz** [comment]
[This is the component](https://github.com/moroshko/react-autosuggest) we're using for showing suggestions, maybe you can look there if there's a way to stop the cycling once you get to the bottom.

Notice that it takes two keystrokes currently to get back to the top, and the edges of the last element are rounded, to show that that you reached the end of the suggestion list. I wouldn't think that's confusing, but honestly I never go past the first 3 suggestions.
